//
//  ClipboardMonitor.swift
//  Recall
//
//  macOS has no pasteboard-change notification, so we poll changeCount.
//  The timer tolerance lets the system coalesce our wakeups to save power.
//

import AppKit

final class ClipboardMonitor {
    private var timer: Timer?
    private var lastChangeCount: Int
    private let pasteboard = NSPasteboard.general

    /// Set when we write to the pasteboard ourselves, so we skip our own change.
    var expectedChangeCount: Int = -1

    init() {
        lastChangeCount = pasteboard.changeCount
    }

    func start() {
        guard timer == nil else { return }
        // Ignore whatever was copied while we weren't watching (e.g. paused).
        lastChangeCount = pasteboard.changeCount
        let t = Timer(timeInterval: 0.5, repeats: true) { [weak self] _ in
            MainActor.assumeIsolated { self?.tick() }
        }
        t.tolerance = 0.25
        RunLoop.main.add(t, forMode: .common)
        timer = t
    }

    func stop() {
        timer?.invalidate()
        timer = nil
    }

    private func tick() {
        let count = pasteboard.changeCount
        guard count != lastChangeCount else { return }
        lastChangeCount = count
        guard !ClipboardStore.shared.isPaused else { return }
        guard count != expectedChangeCount else { return }

        let types = pasteboard.types ?? []

        // Respect the org.nspasteboard convention used by password managers.
        let skipMarkers = [
            "org.nspasteboard.TransientType",
            "org.nspasteboard.ConcealedType",
            "org.nspasteboard.AutoGeneratedType",
        ]
        if types.contains(where: { skipMarkers.contains($0.rawValue) }) { return }

        let front = NSWorkspace.shared.frontmostApplication
        let appName = front?.localizedName
        let bundleID = front?.bundleIdentifier

        // File copies take priority over their text representation.
        if types.contains(.fileURL),
           let urls = pasteboard.readObjects(forClasses: [NSURL.self]) as? [URL],
           !urls.isEmpty {
            ClipboardStore.shared.ingest(fileURLs: urls, appName: appName, appBundleID: bundleID)
            return
        }

        if types.contains(.png) || types.contains(.tiff) {
            let data = pasteboard.data(forType: .png) ?? pasteboard.data(forType: .tiff)
            if let data, data.count < 64 * 1024 * 1024 {
                ClipboardStore.shared.ingest(imageData: data, appName: appName, appBundleID: bundleID)
                return
            }
        }

        if let text = pasteboard.string(forType: .string),
           !text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty,
           text.utf8.count < 4 * 1024 * 1024 {
            ClipboardStore.shared.ingest(text: text, appName: appName, appBundleID: bundleID)
        }
    }
}
